# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197huyxeDKXrC7iZGzScDWRDbg6NZ6NS2

# set-up and import
"""

import requests
import json
import re
import zipfile
from flask import Flask,request,abort
from app.Config import *
from pythainlp.tokenize import word_tokenize
from pythainlp.util import dict_trie
from pythainlp.corpus.common import thai_words
from pythainlp.corpus import thai_stopwords
from pythainlp.spell import correct
import pandas as pd
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
import tensorflow as tf

"""# Loaded Model & CSV"""

loaded_model = tf.keras.models.load_model("app/my_model")

df = pd.read_csv("app/dataset.csv")

"""# Word Index"""

custom_words_list = set(thai_words())
# custom_words_list.update(words)
trie = dict_trie(dict_source=custom_words_list)

STOP_WORD = list(thai_stopwords()) + [" ", "\n"]
FORMAT = r"[\u0E00-\u0E7Fa-zA-Z'0-9]+"


def suggested_words(sentence):
  return [correct(word) for word in sentence]

def tokenize(sentence):
  return word_tokenize(sentence, engine="attacut", custom_dict=trie, keep_whitespace=False)

def cleaning_stop_word(tk_list):
  return [word for word in tk_list if word not in STOP_WORD]

def cleaning_symbols_emoji(tk_list):
  return [re.findall(FORMAT, text)[0] for text in tk_list if re.findall(FORMAT, text)]

def worm_split(sentence):
  return sentence.split("~")

dataset = df.data.apply(worm_split)

tokenizer = Tokenizer()
tokenizer.fit_on_texts(dataset)

tts = tokenizer.texts_to_sequences(dataset)
maxlen = max([len(s) for s in tts])

"""# Webhook Line"""

app=Flask(__name__)

@app.route('/webhook',methods=['POST','GET'])

def webhook():
    if request.method=='POST':
        payload =request.json
        Reply_token=payload['events'][0]['replyToken']
        message=payload['events'][0]['message']['text']
        message_df = pd.DataFrame({"question": [message]})
        tokenized_message = message_df.question.astype(str).apply(tokenize).apply(cleaning_symbols_emoji).apply(cleaning_stop_word).apply(suggested_words)
        message_tts = tokenizer.texts_to_sequences(tokenized_message)
        message_padding = pad_sequences(message_tts, maxlen=maxlen, padding="post")
        logit = loaded_model.predict(message_padding)
        predict = np.argmax(logit)
        if "สวัสดี" in message:
          Reply_text = "สวัสดีครับผม คือ แชทบอทให้ความรู้เกี่ยวกับกระท่อมในไทยครับ\n"+\
                        "นี่คือหัวข้อที่ผมอาจตอบคำถามของคุณได้:\n"+\
                        "-อาหาร\n"+\
                        "-เครื่องดื่ม\n"+\
                        "-วิธีการปลูก\n"+\
                        "-การดูแล\n"+\
                        "-การขยายพันธุ์\n"+\
                        "-ข้อดี\n"+\
                        "-ข้อเสีย\n"+\
                        "-ลักษณะและแหล่งกำเนิด\n"+\
                        "-การบริโภคและค้าขาย"
        elif (np.max(logit) < 0.5):
          Reply_text = "ขอโทษครับ คำถามนี้อาจไม่อยู่ในรายการคำถามที่ผมได้รับการฝึกฝน\n"+\
                        "อาจเกี่ยวกับเรื่องที่ผมไม่มีความรู้\n"+\
                        "หรือช่วยตรวจสอบข้อความที่พิมพ์อีกทีว่าตกหล่นอะไรไหม"
        elif (predict == 0):
           Reply_text = "กระท่อมสามารถทำมาทำอาหารได้ไม่ว่าจะ ต้ม ผัด หรือทอด\n"+\
                         "นี้คือตัวอย่างอาหารที่ทำจากกระท่อมที่คุณสนใจ\n"+\
                         "- “ใบกระท่อมชุบแป้งทอด” เมนูฮิตจากประเทศเพื่อนบ้าน มาเลเซีย\n"+\
                         "   โดยนิยมกินเป็นอาหารเช้าคู่กับ กาแฟ\n"+\
                         "- “กระท่อมในซอสอาหารต่าง” เป็นการประยุกต์ใส่ กระท่อมผง ลงในซอสสำหรับปรุงอาหาร\n"+\
                         "- “บราวนี่กระท่อม” ใช้กระท่อมผง เป็นส่วนผสม แบบเดียวกับ กัญชา\n"+\
                         "   หรือผสมรวมกันเป็นบราวนี่สมุนไพร รสช็อกโกแลตในขนม และน้ำตาลจะช่วยกลบความขมของกระท่อมได้\n"+\
                            "หาข้อมูลเพิ่มได้ที่ https://shorturl.at/dimnK"
        elif (predict == 1):
           Reply_text = "รสชาติของน้ำกระท่อมจะขมคล้ายบอระเพ็ด\n"+\
                         "เฝิ่นๆ ฝาดๆ เหมือนสมุนไพร\n"+\
                         "หลังดื่มจะรู้สึกไม่ค่อยร้อนเมื่ออยู่กลางแจ้ง\n"+\
                         "สามารถดูสูตรทำน้ำกระท่อมได้ที่ https://shorturl.at/wxB39"
        elif (predict == 10):
           Reply_text = "การปลูกกระท่อม\n"+\
                         "ระยะการปลูกกระท่อม ปลูกระยะ 4X4 เมตร พื้นที่ 1 ไร่ สามารถปลูกได้ 100 ต้น\n"+\
                         "ดินและน้ำสำหรับปลูกกระท่อม ดินที่ใช้ปลูกกระท่อม ควรเป็นดินร่วนซุย\n"+\
                         "ควรมีน้ำอย่างทั่วถึง และปลูกกลางแจ้งเพื่อลดโรคเชื้อราจุดดำได้ หรือเอาน้ำปูนขาวละลายรดหรือฉีด\n"+\
                         "ศึกษาต่อได้ที่ https://shorturl.at/bklyL"
        elif (predict == 11):
           Reply_text = "การเตรียมดิน สำหรับพืชกระท่อมเสียบยอด จะเหมาะกับการปลูกในพื้นที่นาที่ลุ่มมีน้ำทั่วถึง\n"+\
                         "การเตรียมดินจึงไม่มีปัญหายุ่งยาก เพราะเหมาะกับปลูกในสภาพพื้นที่มีน้ำขังอยู่แล้ว\n"+\
                         "หรืออาจจะมีการยกร่องเปิดทางน้ำให้ไหลสักเล็กน้อย\n"+\
                         "สำหรับกระท่อมที่ขยายพันธุ์โดยการเสียบยอดจะชอบน้ำมากกว่าการปลูกกระท่อมด้วยเมล็ด\n"+\
                         "การดูแลรดน้ำ กระท่อมเป็นพืชที่ชอบน้ำ ถ้าปลูกในที่น้ำขัง ก็ไม่ต้องกังวลอะไรมาก\n"+\
                         "แต่ถ้าหากเป็นพื้นที่มีการเตรียมดิน มีการปรับแต่งพื้นที่ให้ทำการรดน้ำโดยเฉลี่ย 1-2 วันครั้ง\n"+\
                         "นานประมาณ 30 นาที ให้เกิดความชุ่มชื้น\n"+\
                         "การใส่ปุ๋ย เน้นใส่ปุ๋ยคอก ในทุกๆ 20-30 วัน ใส่ปุ๋ย 1 ครั้ง\n"+\
                         "การเก็บเกี่ยว สำหรับที่เป็นต้นพันธุ์เสียบยอดใช้ระยะเวลาการปลูกจนถึงเก็บเกี่ยวประมาณ 3-5 เดือน\n"+\
                         "จากนั้นสามารถเก็บผลผลิตได้ในทุกๆ 15 วัน ปลูกครั้งเดียวเก็บได้นานหลายสิบปี\n"+\
                         "เมื่อต้นสูงเกินความจำเป็นต้องใช้วิธีการตัดยอดด้านบนเพื่อให้ต้นแผ่กิ่งข้างได้อย่างเต็มที่\n"+\
                         "ทำให้ง่ายต่อการเก็บเกี่ยว ส่วนปริมาณผลผลิตนั้นยังบอกไม่ได้แน่ชัด\n"+\
                         "เนื่องจากตอนนี้ยังอยู่ในจุดเริ่มต้นขยายพันธุ์ แต่หากจะให้คาดการณ์ผลผลิตล่วงหน้า 1 ไร่\n"+\
                         "จะสามารถเก็บผลผลิตได้ ประมาณ 500 กิโลกรัม\n"+\
                         "โดยเฉพาะหากเป็นต้นที่มีอายุเยอะปริมาณก็จะเพิ่มขึ้นตามไปด้วย\n"+\
                         "สนใจศึกษาเพิ่มเติม https://shorturl.at/lwEH6"
        elif (predict == 12):
           Reply_text = "การขยายพันธุ์กระท่อมมีหลักอยู่ 3 วิธี คือ การเพาะเมล็ด การชำกิ่ง และการเสียบยอด\n"+\
                         "ซึ่งการชำกิ่งในระยะเวลาประมาณ 5 ปีแรกต้นไม้จะโตได้อย่างรวดเร็ว\n"+\
                         "แต่หลังจากนั้นก็จะเริ่มโตช้า สุดท้ายในระยะเวลาประมาณ 10 ปี\n"+\
                         "ก็จะได้ขนาดต้นพอๆกับการต้นไม้ที่เกิดจากการเพาะเมล็ดอยู่ดี\n"+\
                         "แต่อย่างไรก็ตามการเพาะเมล็ดจะทำให้คุณภาพและรสชาติของกระท่อม\n"+\
                         "สนใจศึกษาต่อเพิ่มเติมได้ที่ https://shorturl.at/krKX4"
        elif (predict == 20):
          Reply_text = "พืชกระท่อมให้ประโยชน์ในเรื่องของช่วย บรรเทาอาการปวด บรรเทาอาการไอ\n"+\
                        "- ช่วยลดการหลั่งกรดในกระเพาะ\n"+\
                        "- ช่วยทําให้นอนหลับ\n"+\
                        "- ช่วยทําให้เรามีสมาธิมากขึ้น\n"+\
                        "แล้วยังมีการศึกษาวิจัยเบื้องต้นว่า พืชกระท่อมยังสามารถใช้ทดแทนยามอร์ฟีนที่ได้รับปวดได้\n"+\
                        "เพียงแต่จะมีฤทธิ์น้อยกว่าสิบเท่า แต่ข้อดีก็คือผลข้างเคียงที่จะกดอาการหายใจ\n"+\
                        "หรือทําให้เกิดคลื่นไส้อาเจียนก็จะน้อยตามลง\n"+\
                        "สนใจศึกษาต่อเพิ่มเติมได้ที่ https://shorturl.at/gsV16"
        elif (predict == 21):
           Reply_text = "โทษของกระท่อม\n"+\
                         "- ทําให้เราไม่อยากอาหาร ท้องผูก เหงื่อออก ปัสสาวะบ่อย\n"+\
                         "- ทําให้เราวิตกกังวล หัวใจเต้นเร็วขึ้น\n"+\
                         "- อาจทําให้เรามีอาการแพ้แสง\n"+\
                         "- ทําให้สีผิวเราเข้ม แล้วก็คล้ําขึ้นนั่นเองค่ะ\n"+\
                         "แต่ถ้าเราเสพในปริมาณมากๆ ผลข้างเคียงที่ร้ายแรงของมันก็คือ ทําให้เราเกิดการประสาทหลอนนั่นเอง\n"+\
                         "สนใจศึกษาต่อเพิ่มเติมได้ที่ https://shorturl.at/fgozR"
        elif (predict == 30):
           Reply_text = "ลักษณะทางกายภาพ:\n"+\
                         "ต้น: มีก้านใบยาวและถูกแบ่งเป็นก้านใบเล็ก ๆ ที่มีใบเป็นรูปเพดานทรงกระบอกหรือทรงรี\n"+\
                         "ใบ: ใบมีลักษณะยาวและแคบ มีสีเขียวเข้ม\n"+\
                         "ดอก: ไม่ต้องออกดอกเพื่อผสมเกสร เพราะการผสมเกสรเกิดขึ้นในต้นเดียว\n"+\
                         "ผล: มีผลเป็นลูกเปลือกแข็งที่มีเนื้อภายในเป็นกลีบน้ำและมีก้านลูก\n"+\
                         "แหล่งกำเนิดของพืชกระท่อม:\n"+\
                         "พืชกระท่อมเป็นพืชที่มีลักษณะทางชีวภาพที่เหมาะสมกับสภาพแวดล้อมในท้องถิ่นที่มีอากาศร้อนและชื้น\n"+\
                         "ซึ่งทำให้พืชนี้สามารถเจริญเติบโตได้ดีในภูมิภาคเอเชียตะวันออก, ใต้จีน,\n"+\
                         "และแถบชายฝั่งตะวันตกของแอฟริกา\n"+\
                         "สนใจศึกษาต่อเพิ่มเติมได้ที่ https://shorturl.at/btGKS\n"+\
                         "หรือ https://shorturl.at/pwABJ"
        elif (predict == 40):
           Reply_text = "-กฎหมายฉบับนี้จะมีผลในอีก 90 วัน นับจากวันประกาศในพระราชกฤษฎีกา หรือ\n"+ \
                        " 26 พฤษภาคม 2564 ดังนั้น นับไปอีกราว 3 เดือนถึงจะมีผลบังคับใช้\n" +\
                        "-มาตรา 3 ในกฎหมายฉบับนี้ มีผลให้ถอดกระท่อมออกจากบัญชียาเสพติดประเภท 5\n"+ \
                        " กล่าวคือหลังจากนี้ กระท่อมจะไม่ใช่ยาเสพติดอีกต่อไป\n"+\
                        "-มาตรา 4 มีผลทำให้ 90 วันหลังจากนี้ พื้นที่ชุมชนที่เคยเป็นพื้นที่นำร่องปลูกกระท่อม\n"+ \
                        " ตามนโยบายกระทรวงยุติธรรม และสามารถใช้กระท่อมเพื่อการบริโภคได้ จะไม่มีอีกต่อไป\n"+\
                        "-ให้ยกเลิกกฎหมายมาตรา 75,76, 76/1 และ 92 ใน พ.ร.บ.ยาเสพติดให้โทษ พ.ศ.2522\n"+ \
                        " ซึ่งกฎหมายทั้งสี่มาตราระบุโทษปรับและอาญาสำหรับการครอบครอง เสพ ค้าขาย\n"+ \
                        " จนถึงนำเข้าและส่งออกสำหรับยาเสพติดประเภท 5 ซึ่งภายหลังกฎหมายฉบับล่าสุดประกาศใช้\n"+ \
                        " กระท่อมจะไม่ใช่ยาเสพติดประเภทใดๆ อีกต่อไป จึงจะไม่มีโทษที่เคยกำหนดตามกฎหมาย\n" +\
                        " สนใจศึกษาต่อเพิ่มเติมได้ที่ https://shorturl.at/ovw39"
        print(Reply_text,flush=True)
        ReplyMessage(Reply_token,Reply_text,Channel_access_token)
        return request.json,200
    elif request.method=='GET':
        return "this is method GET!!!",200
    else:
        abort(400)


def ReplyMessage(Reply_token,TextMessage,Line_Acees_Token):
    LINE_API='https://api.line.me/v2/bot/message/reply/'

    Authorization='Bearer {}'.format(Line_Acees_Token)
    print(Authorization)
    headers={
        'Content-Type':'application/json; char=UTF-8',
        'Authorization':Authorization
    }

    data={
        "replyToken":Reply_token,
        "messages":[{
            "type":"text",
            "text":TextMessage
        }
        ]
    }
    data=json.dumps(data) # ทำเป็น json
    r=requests.post(LINE_API,headers=headers,data=data)
    return 200

